version: "3"

services:
  app:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN?:TELEGRAM_TOKEN}
    command: sleep infinity
    ports:
      - "5000:5000"
    volumes:
      - ./:/workspace
      - ./m2-docker:/home/vscode/.m2
