@host=api.telegram.org/bot
@token={{$processEnv TELEGRAM_TOKEN}}
@url = {{host}}{{token}}
@webhookUrl = https://1c6937723e82.ngrok.io/bot

// @name getMe
GET https://{{url}}/getMe

###

// @name getWebhookInfo
GET https://{{url}}/getWebhookInfo

###

// @name setWebhook
POST https://{{url}}/setWebhook
Content-Type: application/json

{
  "url": "{{webhookUrl}}"
}
