@host=api.telegram.org/bot
@token={{$processEnv TELEGRAM_TOKEN}}
@url = {{host}}{{token}}

// @name getMe
GET https://{{url}}/getMe

###

// @name getWebhookInfo
GET https://{{url}}/getWebhookInfo

###

// @name setWebhook
POST https://{{url}}/setWebhook
Content-Type: application/json

{
  "url": "https://776bc19c9ffe.ngrok.io/bot",
}
